// ################################## DO NOT EDIT THIS FILE ######################################
// ### Common Sense Coding (https://github.com/cscoding21/csgen)

// This file contains generated code. DO NOT EDIT.
// Generate Date: 2024-06-11 10:15:56.531924779 -0700 PDT m=+0.211474745
// Implementation Name: csmap

// -----------------------------------------------------------------------------------------------

package tests

import (
	"github.com/cscoding21/csmap/tests/pkgco"
	"github.com/cscoding21/csmap/utils"
)

// PagingSourcePkgcoToPkgco converts the source object to the target object.
func PagingSourcePkgcoToPkgco(r pkgco.PagingSource) pkgco.PagingTarget {
	out := pkgco.PagingTarget{
		Page:  r.Page,
		Size:  r.Size,
		Token: r.Token,
	}

	return out
}

// PagingSourcePkgcoToPkgcoSlice converts the source object slice to the target object slice.
func PagingSourcePkgcoToPkgcoSlice(r []*pkgco.PagingSource) []*pkgco.PagingTarget {
	out := []*pkgco.PagingTarget{}

	for _, v := range r {
		out = append(out, utils.ValToRef(PagingSourcePkgcoToPkgco(*v)))
	}

	return out
}
