// Code generated . DO NOT EDIT.
// ################################## DO NOT EDIT THIS FILE ######################################
// Common Sense Coding (https://github.com/cscoding21/csgen)

// Generate Date: 2024-06-13 15:00:19.863558368 -0700 PDT m=+0.217447481
// Implementation Name: csmap

// -----------------------------------------------------------------------------------------------

package tests

import (
	"github.com/cscoding21/csmap/tests/pkgco"
	"github.com/cscoding21/csmap/utils"
)

// PagingSourcePkgcoToPkgco converts the source object to the target object.
func PagingSourcePkgcoToPkgco(r pkgco.PagingSource) pkgco.PagingTarget {
	out := pkgco.PagingTarget{
		Page:  r.Page,
		Size:  r.Size,
		Token: r.Token,
	}

	return out
}

// PagingSourcePkgcoToPkgcoSlice converts the source object slice to the target object slice.
func PagingSourcePkgcoToPkgcoSlice(r []*pkgco.PagingSource) []*pkgco.PagingTarget {
	out := []*pkgco.PagingTarget{}

	for _, v := range r {
		out = append(out, utils.ValToRef(PagingSourcePkgcoToPkgco(*v)))
	}

	return out
}
